name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk
        pip install buildozer cython==0.29.36

    - name: Compilar APK
      run: |
        buildozer -v android debug

    - name: Guardar APK
      uses: actions/upload-artifact@v4
      with:
        name: ControlBus APK
        path: bin/*.apk
