name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git unzip zip wget \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.37

      - name: Install Android SDK
        run: |
          SDK=$HOME/.buildozer/android/platform/android-sdk

          mkdir -p $SDK
          cd /tmp

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip

          unzip -q commandlinetools-linux-9477386_latest.zip

          mkdir -p $SDK/cmdline-tools/latest

          mv cmdline-tools/* $SDK/cmdline-tools/latest/

          mkdir -p $SDK/tools/bin

          ln -sf $SDK/cmdline-tools/latest/bin/sdkmanager $SDK/tools/bin/sdkmanager
          ln -sf $SDK/cmdline-tools/latest/bin/avdmanager $SDK/tools/bin/avdmanager

          echo "ANDROID_HOME=$SDK" >> $GITHUB_ENV
          echo "ANDROIDSDK=$SDK" >> $GITHUB_ENV

          echo "$SDK/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$SDK/tools/bin" >> $GITHUB_PATH

      - name: Verify SDK
        run: |
          which sdkmanager
          sdkmanager --version

      - name: Accept licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android packages
        run: |
          sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

          ls -R $ANDROIDSDK/build-tools

      - name: Clean Buildozer
        run: |
          rm -rf .buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlBus-apk
          path: bin/*.apk
