name: Build Android APK

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-22.04


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4



    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"



    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"



    - name: Install system dependencies
      run: |

        sudo apt update

        sudo apt install -y \
          git \
          unzip \
          zip \
          wget \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake



    - name: Install Buildozer
      run: |

        python -m pip install --upgrade pip

        pip install buildozer

        pip install cython==0.29.37



    - name: Setup Android SDK
      run: |

        mkdir -p $HOME/.buildozer/android/platform/android-sdk


        cd /tmp


        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip


        unzip -q commandlinetools-linux-9477386_latest.zip


        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest


        mv cmdline-tools/* \
        $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/


        # Compatibilidad con Buildozer
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin


        ln -sf \
        $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
        $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager


        ln -sf \
        $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/avdmanager \
        $HOME/.buildozer/android/platform/android-sdk/tools/bin/avdmanager



        echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV


        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        echo "$HOME/.buildozer/android/platform/android-sdk/tools/bin" >> $GITHUB_PATH



    - name: Check sdkmanager
      run: |

        sdkmanager --version

        which sdkmanager



    - name: Accept Android licenses
      run: |

        yes | sdkmanager --licenses || true



    - name: Install Android packages
      run: |

        sdkmanager \
          "platform-tools" \
          "platforms;android-35" \
          "build-tools;35.0.0"



        echo "Installed Build Tools:"

        ls $ANDROIDSDK/build-tools



    - name: Clean previous Buildozer files
      run: |

        rm -rf .buildozer

        rm -rf ~/.buildozer/android/platform/python-for-android



    - name: Build APK
      run: |

        buildozer -v android debug



    - name: Upload APK
      uses: actions/upload-artifact@v4

      with:

        name: ControlBus-apk

        path: bin/*.apk
